# Generated by Django 5.1.7 on 2025-03-28 13:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apskritis',
            name='ribos',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='savivaldybe',
            name='ribos',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='seniunija',
            name='ribos',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
