# Generated by Django 5.1.7 on 2025-07-10 12:32

import apps.address_registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeunit',
            name='type',
            field=models.CharField(choices=apps.address_registry.models.get_administrative_unit_type, max_length=255, null=True),
        ),
    ]
