# Generated by Django 5.1.7 on 2025-07-14 11:39

import apps.address_registry.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_registry', '0002_apskritis_ribos_savivaldybe_ribos_seniunija_ribos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Continent',
                'verbose_name_plural': 'Continents',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('received', models.DateField()),
                ('content', models.BinaryField()),
                ('status', models.CharField(choices=apps.address_registry.models.get_doc_status, max_length=255)),
                ('type', models.CharField(choices=apps.address_registry.models.get_doc_type, max_length=255)),
                ('creation_date', models.DateField()),
                ('creation_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.RemoveField(
            model_name='savivaldybe',
            name='apskritis',
        ),
        migrations.RemoveField(
            model_name='savivaldybe',
            name='dokumentai',
        ),
        migrations.RemoveField(
            model_name='dokumentoautorius',
            name='dokumentas',
        ),
        migrations.RemoveField(
            model_name='seniunija',
            name='dokumentai',
        ),
        migrations.RemoveField(
            model_name='gyvenviete',
            name='salis',
        ),
        migrations.RemoveField(
            model_name='savivaldybe',
            name='centras',
        ),
        migrations.RemoveField(
            model_name='seniunija',
            name='centras',
        ),
        migrations.RemoveField(
            model_name='pavadinimas',
            name='gyvenviete',
        ),
        migrations.RemoveField(
            model_name='juridinisasmuo',
            name='organizacija_ptr',
        ),
        migrations.RemoveField(
            model_name='nejuridinisasmuo',
            name='organizacija_ptr',
        ),
        migrations.RemoveField(
            model_name='seniunija',
            name='salis',
        ),
        migrations.RemoveField(
            model_name='savivaldybe',
            name='salis',
        ),
        migrations.RemoveField(
            model_name='seniunija',
            name='savivaldybe',
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('title_lt', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_registry.continent')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.FloatField(null=True)),
                ('registered', models.DateField(null=True)),
                ('deregistered', models.DateField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('area', models.FloatField(null=True)),
                ('type', models.CharField(choices=apps.address_registry.models.get_administrative_unit_type, max_length=255)),
                ('country_code', models.CharField(help_text='Must match with country_id', max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_registry.country')),
            ],
            options={
                'verbose_name': 'Administrative Unit',
                'verbose_name_plural': 'Administrative Units',
            },
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_registry.administrativeunit')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_registry.country')),
            ],
            options={
                'verbose_name': 'Administration',
                'verbose_name_plural': 'Administrations',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_registry.administrativeunit')),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='DocumentAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('passport', models.FileField(null=True, upload_to='passport')),
                ('document', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address_registry.document')),
            ],
            options={
                'verbose_name': 'Document Author',
                'verbose_name_plural': 'Document Authors',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_registry.administrativeunit')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_registry.county')),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
            },
        ),
        migrations.CreateModel(
            name='Eldership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_registry.administrativeunit')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_registry.municipality')),
            ],
            options={
                'verbose_name': 'Eldership',
                'verbose_name_plural': 'Elderships',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.DateField(null=True)),
                ('deregistered', models.DateField(null=True)),
                ('title_lt', models.CharField(max_length=255)),
                ('area', models.FloatField(null=True)),
                ('type', models.CharField(choices=apps.address_registry.models.get_settlement_type, max_length=255)),
                ('country_code', models.CharField(help_text='Must match with country_id', max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_registry.country')),
            ],
            options={
                'verbose_name': 'Settlement',
                'verbose_name_plural': 'Settlements',
            },
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_registry.settlement'),
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('accented', models.CharField(max_length=255)),
                ('grammatical_case', models.CharField(choices=apps.address_registry.models.get_grammatical_case, max_length=255)),
                ('settlement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_forms', to='address_registry.settlement')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
            },
        ),
        migrations.DeleteModel(
            name='Apskritis',
        ),
        migrations.DeleteModel(
            name='DokumentoAutorius',
        ),
        migrations.DeleteModel(
            name='Dokumentas',
        ),
        migrations.DeleteModel(
            name='Gyvenviete',
        ),
        migrations.DeleteModel(
            name='Pavadinimas',
        ),
        migrations.DeleteModel(
            name='JuridinisAsmuo',
        ),
        migrations.DeleteModel(
            name='NejuridinisAsmuo',
        ),
        migrations.DeleteModel(
            name='Organizacija',
        ),
        migrations.DeleteModel(
            name='Salis',
        ),
        migrations.DeleteModel(
            name='Savivaldybe',
        ),
        migrations.DeleteModel(
            name='Seniunija',
        ),
    ]
