# Generated by Django 5.1.7 on 2025-07-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_registry', '0002_alter_administrativeunit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administration',
            old_name='administration_country',
            new_name='country',
        ),
    ]
