# Generated by Django 5.1.7 on 2025-07-10 13:18

import apps.address_registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_registry', '0003_rename_administration_country_administration_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeunit',
            name='type',
            field=models.CharField(choices=apps.address_registry.models.get_administrative_unit_type, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
