# Generated by Django 5.1.7 on 2025-07-21 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_registry', '0003_continent_document_remove_savivaldybe_apskritis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='address_registry.continent'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='address_registry.country'),
        ),
    ]
