# Generated by Django 5.1.7 on 2025-07-11 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_registry', '0004_alter_administrativeunit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldership',
            name='municipality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address_registry.municipality'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='municipality',
            name='county',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address_registry.county'),
            preserve_default=False,
        ),
    ]
