# Generated by Django 4.0.6 on 2022-10-24 17:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_version', models.CharField(default='1', max_length=300)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
